version: '3.7'  
 
services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8.0
    command:
      --sql-mode=''      
      --lower-case-table-names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --default-storage-engine=InnoDB
#      --authentication-policy=mysql_native_password,,  # MySQL client 5.7 compatibility
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql
 
volumes:
  mysql-data:
  mysql-conf:
