version: "3.7"

services:
  ansible:
    image: ansible:latest
    container_name: ansible
    restart: always

    # Make inventories, collections, roles and vault available through volumes
    volumes:
      - ./inventories:/home/ebo/ansible/inventories
      - ./playbooks:/home/ebo/ansible/playbooks
      - ./collections:/home/ebo/ansible/collections
      - ./roles:/home/ebo/ansible/roles
      - ./vault:/home/ebo/ansible/vault
