version: "3.8"

services:
  ansible:
    image: ansible:latest
    container_name: ansible
    restart: always

    # Make inventories, collections, roles and vault available through volumes
    volumes:
      # Molecule
      - /var/run/docker.sock:/var/run/docker.sock
      # Settings
      - ./ansible.cfg:/home/ansible/.ansible.cfg
      # Utilities
      - ./inventories:/home/ansible/inventories
      - ./playbooks:/home/ansible/playbooks
      - ./requirements:/home/ansible/requirements
      - ./collections:/home/ansible/collections
      - ./roles:/home/ansible/roles
      - ./vault:/home/ansible/vault
