version: '3.7'
 
services:
  mysql5.7:
    image: mysql:5.7
    container_name: mysql5.7
    command:
      --sql-mode=''      
      --lower-case-table-names=1
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-storage-engine=InnoDB
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql
 
volumes:
  mysql-data:
  mysql-conf:
